name: Custom Jellyseerr Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  update-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout upstream (Fallenbagel/jellyseerr repository)
        uses: actions/checkout@v3
        with:
          repository: Fallenbagel/jellyseerr
          ref: main
          
      - name: Force correct pnpm version in Dockerfile
        run: |
          sed -i 's|npm install --global pnpm[[:space:]]*$|npm install --global pnpm@9|' Dockerfile
          
      - name: Copy custom assets from your repository
        run: |
          mkdir -p custom-assets public/images public/
          curl -o custom-assets/logo_full.png https://raw.githubusercontent.com/AIndoria/vespera/main/custom-assets/logo_full.png
          curl -o custom-assets/logo_stacked.png https://raw.githubusercontent.com/AIndoria/vespera/main/custom-assets/logo_stacked.png
          cp custom-assets/logo_full.png public/images/logo_full.png
          cp custom-assets/logo_stacked.png public/images/logo_stacked.png
          cp custom-assets/logo_full.png public/logo_full.png
          cp custom-assets/logo_stacked.png public/logo_stacked.png

      - name: Update references for logos
        run: |
          # Replace all instances of logo_full.svg/stacked.svg with .png across the project
          find . -type f \( -name "*.tsx" -o -name "*.jsx" -o -name "*.html" -o -name "*.js" \) \
            -exec sed -i 's|logo_full\.svg|logo_full.png|g' {} +
          find . -type f \( -name "*.tsx" -o -name "*.jsx" -o -name "*.html" -o -name "*.js" \) \
            -exec sed -i 's|logo_stacked\.svg|logo_stacked.png|g' {} +

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            COMMIT_TAG=${{ github.sha }}
          tags: |
            aindoria/vespera:latest
