name: Custom Jellyseerr Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  update-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0  # Add this to fetch complete history

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # First, save your custom assets
      - name: Backup custom assets
        run: |
          mkdir -p /tmp/custom-assets
          cp -r custom-assets/* /tmp/custom-assets/

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/Fallenbagel/jellyseerr.git
          git fetch upstream
          git reset --hard upstream/main

      # Restore your custom assets
      - name: Restore custom assets
        run: |
          mkdir -p custom-assets
          cp -r /tmp/custom-assets/* custom-assets/

      - name: Replace logo files and references
        run: |
          # Replace physical files
          cp custom-assets/logo_full.png public/images/logo_full.svg
          cp custom-assets/logo_stacked.png public/images/logo_stacked.svg
          
          # Find and replace all references in files
          find . -type f -exec sed -i 's/logo_full\.svg/logo_full.png/g' {} +
          find . -type f -exec sed -i 's/logo_stacked\.svg/logo_stacked.png/g' {} +

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            COMMIT_TAG=${{ github.sha }}
          tags: |
            aindoria/vespera:latest

      - name: Push changes back to fork
        run: |
          git add .
          git commit -m "Auto-update from upstream and replace logos" || echo "No changes to commit"
          git push -f origin main
