name: Custom Jellyseerr Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  update-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout upstream directly
        uses: actions/checkout@v3
        with:
          repository: Fallenbagel/jellyseerr
          ref: main

      - name: Copy custom assets
        run: |
          mkdir -p custom-assets
          curl -o custom-assets/logo_full.png https://raw.githubusercontent.com/AIndoria/vespera/main/custom-assets/logo_full.png
          curl -o custom-assets/logo_stacked.png https://raw.githubusercontent.com/AIndoria/vespera/main/custom-assets/logo_stacked.png

      - name: Replace logo files and references
        run: |
          # Copy to public/images with both extensions
          cp custom-assets/logo_full.png public/images/logo_full.svg
          cp custom-assets/logo_full.png public/images/logo_full.png
          cp custom-assets/logo_stacked.png public/images/logo_stacked.svg
          cp custom-assets/logo_stacked.png public/images/logo_stacked.png
          
          cp custom-assets/logo_full.png public/logo_full.svg
          cp custom-assets/logo_full.png public/logo_full.png
          cp custom-assets/logo_stacked.png public/logo_stacked.svg
          cp custom-assets/logo_stacked.png public/logo_stacked.png
          
          find ./src -type f -name "*.tsx" -exec sed -i 's|"/images/logo_full.svg"|"/images/logo_full.svg?v=custom"|g' {} +
          find ./src -type f -name "*.tsx" -exec sed -i 's|"/images/logo_stacked.svg"|"/images/logo_stacked.svg?v=custom"|g' {} +

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            COMMIT_TAG=${{ github.sha }}
          tags: |
            aindoria/vespera:latest
